shellEmulator: true
trustPolicy: no-downgrade

overrides:
  citty: ^0.2.1
  eslint: ^10.0.2
  jsonc-eslint-parser: ^3.1.0

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - vue-demi
