minimumReleaseAgeExclude:
  - '@zvonimirsun/iszy-nuxt-auth-layer@0.1.5'

shellEmulator: true
blockExoticSubdeps: false

overrides:
  citty: ^0.2.2
  eslint: ^10.4.1
  jsonc-eslint-parser: ^3.1.0
  typescript: ^6.0.3
  vue-router: ^5.1.0
  xlsx: https://cdn.sheetjs.com/xlsx-0.19.3/xlsx-0.19.3.tgz#sha512-8IfgFctB7fkvqkTGF2MnrDrC6vzE28Wcc1aSbdDQ+4/WFtzfS73YuapbuaPZwGqpR2e0EeDMIrFOJubQVLWFNA==

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi
  - json-editor-vue

onlyBuiltDependencies:
  - vue-demi

allowBuilds:
  '@parcel/watcher': false
  '@zvonimirsun/iszy-nuxt-auth-layer': false
  '@zvonimirsun/map-sdk': false
  core-js: false
  esbuild: false
  json-editor-vue: true
  unrs-resolver: false
  vue-demi: false
