minimumReleaseAgeExclude:
  - '@zvonimirsun/*'

shellEmulator: true
blockExoticSubdeps: false

overrides:
  xlsx: https://cdn.sheetjs.com/xlsx-0.19.3/xlsx-0.19.3.tgz#sha512-8IfgFctB7fkvqkTGF2MnrDrC6vzE28Wcc1aSbdDQ+4/WFtzfS73YuapbuaPZwGqpR2e0EeDMIrFOJubQVLWFNA==

allowBuilds:
  '@parcel/watcher': false
  '@zvonimirsun/iszy-nuxt-auth-layer': false
  '@zvonimirsun/map-sdk': false
  core-js: false
  esbuild: false
  json-editor-vue: true
  unrs-resolver: false
  vue-demi: false
